modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
issueTrackerURL="https://github.com/salvadormg15/Rubber-Duck/issues"

[[mods]]
    modId="rubber_duck"
    version="1.1.1"
    displayName="Rubber Duck"
    updateJSONURL="st.githubusercontent.com/salvadormg15/f73e087096fbc1718d101c6d61389352/raw"
    displayURL="https://github.com/salvadormg15/Rubber-Duck"
    logoFile="rubber_duck.png"
    authors="Salvadormg15"
    description="We just need a Rubber Duck to be happy"

[[dependencies.rubber_duck]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rubber_duck]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1, 1.18)"
    ordering="NONE"
    side="BOTH"
